workspace:
  base: /go
  path: src/github.com/prologic/eris

pipeline:
  build:
    image: golang
    commands:
      - go get -d ./...
      - go build .

  test:
    image: golang
    commands:
      - go get -d ./...
      - go test ./...

  docker:
    image: plugins/docker
    repo: r.mills.io/prologic/eris
    registry: r.mills.io
    secrets: [ docker_username, docker_password ]

  notify:
    image: drillster/drone-email
    host: mail_poste
    port: 25
    from: drone@mills.io
    skip_verify: true 
    when:
      status: [ success, changed, failure ]

secrets:
  registry_username:
    external: true
  registry_password:
    external: true
